### ISSUE TITLE
Publish beta client on GitHub

### ISSUE THREAD

**Issue by baimafeima** [mullvad/oqs-rs#32]
Not sure where to contact you best, so apologies if this is considered off-topic. Could you also publish your beta client (and all subsequent versions as versioned tarballs) here on GitHub to assist users in censorship-affected areas? The current problem is that many need to rely on insecure VPNs to actually access your website and download the client and this can be circumvented by offering versioned tarballs and binaries on GitHub which is rarely censored. In addition to that it would also allow to more effectively collect feedback and track bugs from end users. Thank you.

**Comment by faern** [comment]
@baimafeima Thanks for contacting us. Great suggestion! I assume you are talking about this app: https://mullvad.net/guides/beta-app/

The new VPN app will be open source shortly, before it goes into stable. When we have done that we can publish the releases on the app repository! I'll close this issue and open it in an appropriate internal place for now. Thanks for the suggestion.

**Comment by baimafeima** [comment]
@faern 

> I assume you are talking about this app: https://mullvad.net/guides/beta-app/

Yeah, indeed. Thanks for taking it into consideration and open-sourcing the app here on GitHub.
